[2022-05-29 16:06:24,887] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:24,900] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:24,903] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:24,911] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 16:06:24,914] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:24,981] {taskinstance.py:1378} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-05-28 00:00:00+00:00
[2022-05-29 16:06:24,984] {standard_task_runner.py:52} INFO - Started process 106846 to run task
[2022-05-29 16:06:24,996] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp3gg5h8ae', '--error-file', '/tmp/tmpvym2pj87']
[2022-05-29 16:06:24,998] {standard_task_runner.py:80} INFO - Job 3: Subtask is_api_available
[2022-05-29 16:06:25,182] {task_command.py:370} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-05-28T00:00:00+00:00 [running]> on host airflowvm
[2022-05-29 16:06:25,446] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-29 16:06:25,447] {http.py:97} INFO - Poking: api/
[2022-05-29 16:06:25,455] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-05-29 16:06:25,455] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-05-29 16:06:26,102] {base.py:301} INFO - Success criteria met. Exiting.
[2022-05-29 16:06:26,114] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220528T000000, start_date=20220529T160624, end_date=20220529T160626
[2022-05-29 16:06:26,188] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-29 16:06:26,390] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
